title: Vicky Tang Coaching
url: https://vickytangcoaching.com
remote_theme: huned/hyde@master
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-last-modified-at

# The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: 'Updated %m/%d/%Y'
