# see https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml
# for explanation of config options.

remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
  - jekyll-remote-theme

# Base config
title: Vicky Tang, MD, MAS
author: Vicky Tang, MD, MAS
url: https://vickytangcoaching.com
site-css:
  - "/assets/css/jumbotron.css"
  - "/assets/css/site.css"
  - "https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.css"
  - "https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css"
  - "https://assets.calendly.com/assets/external/widget.css"
site-js:
  - "https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"
  - "/assets/js/testimonials.js"
  - "https://assets.calendly.com/assets/external/widget.js"

# Cosmetic behavior
#avatar: /assets/img/vt-portrait.jpg
#round-avatar: true

# Navbar
navbar-links:
  Book a Call: "https://calendly.com/victoriatang/coaching"
  Email Me: "mailto:vicky.tang@vickytangcoaching.com?subject=Website%20request"
  #Stay in Touch: "https://vickytangcoaching.substack.com"
  #Resources:
  #  - Publications: "https://profiles.ucsf.edu/victoria.tang#toc-id5"
  #  - Linked In: "https://www.linkedin.com/in/vickytangmd/"

# Footer links
social-network-links:
  # substack: vickytangcoaching TODO
  linkedin: vickytangmd
  #telephone: +18325679866
  email: "vicky.tang@vickytangcoaching.com?subject=Website%20request"
  calendly: victoriatang
  # google-scholar: TODO

# Colors
navbar-col: "#b6ffe9"
navbar-text-col: "#404040"
navbar-border-col: "#EAEAEA"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#b6ffe9"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"
